name             'ldap'
maintainer       'Alan Willis'
maintainer_email 'alwillis@riotgames.com'
license          'Apache v2.0'
description      'Provides generic lightweight resources for managing LDAP objects'
version          '1.0.1'
