name             'ldap'
maintainer       'Alan Willis'
maintainer_email 'alwillis@riotgames.com'
source_url       'https://github.com/RiotGamesCookbooks/ldap-cookbook'
license          'Apache v2.0'
description      'Provides generic lightweight resources for managing LDAP objects'
version          '2.0.0'
chef_version     '>= 12.14.89'
